import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	keywords: "next, nextjs, react, javascript",
};

export default function RootLayout({ children }) {
	return (
		<html>
			<body>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	);
}
